from dataclasses import dataclass
from typing import Dict, Any, Optional
import time

@dataclass(frozen=True)
class Event:
    """Base Event structure that all specific events inherit from."""
    timestamp: float

@dataclass(frozen=True)
class MarketEvent(Event):
    """Triggered when new market data is received from the MT5 stream."""
    symbol: str
    bid: float                 # The price we can SELL at
    ask: float                 # The price we can BUY at
    volume: float              # MT5 tick volume
    features: Dict[str, float] # Calculated log returns, volatility metrics, etc.

@dataclass(frozen=True)
class SignalEvent(Event):
    """Generated by the Brain (HMM Engine)."""
    symbol: str
    regime_state: int
    direction: int             # 1 for Long, -1 for Short, 0 for Flat
    strength: float

@dataclass(frozen=True)
class OrderRequestEvent(Event):
    """Generated by Allocation; sent to Safety for inspection."""
    symbol: str
    order_type: str
    side: str
    quantity: float            # Now represents LOTS, not shares
    current_price: float       # Will be the Ask if buying, Bid if selling

@dataclass(frozen=True)
class OrderEvent(Event):
    """Verified order that passed Risk checks."""
    symbol: str
    order_type: str
    side: str
    quantity: float
    reference_id: str

@dataclass(frozen=True)
class FillEvent(Event):
    """Triggered when MT5 confirms execution."""
    symbol: str
    side: str
    quantity: float
    fill_price: float
    commission: float          # Often 0 in Forex, but swaps/spread apply
    execution_id: str